# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'org-process-ui_v03-3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(674, 449)
        MainWindow.setMinimumSize(QtCore.QSize(674, 449))
        MainWindow.setMaximumSize(QtCore.QSize(674, 458))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 80, 651, 281))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelIstd = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelIstd.sizePolicy().hasHeightForWidth())
        self.labelIstd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelIstd.setFont(font)
        self.labelIstd.setObjectName(_fromUtf8("labelIstd"))
        self.gridLayout.addWidget(self.labelIstd, 4, 0, 1, 4)
        self.doubleSpinBoxCalibrationSlope = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxCalibrationSlope.setDecimals(3)
        self.doubleSpinBoxCalibrationSlope.setMinimum(-100.0)
        self.doubleSpinBoxCalibrationSlope.setMaximum(100.0)
        self.doubleSpinBoxCalibrationSlope.setSingleStep(0.001)
        self.doubleSpinBoxCalibrationSlope.setObjectName(_fromUtf8("doubleSpinBoxCalibrationSlope"))
        self.gridLayout.addWidget(self.doubleSpinBoxCalibrationSlope, 8, 7, 1, 1)
        self.doubleSpinBoxCalibrationIntercept = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxCalibrationIntercept.setDecimals(3)
        self.doubleSpinBoxCalibrationIntercept.setMinimum(-100.0)
        self.doubleSpinBoxCalibrationIntercept.setMaximum(100.0)
        self.doubleSpinBoxCalibrationIntercept.setSingleStep(0.001)
        self.doubleSpinBoxCalibrationIntercept.setObjectName(_fromUtf8("doubleSpinBoxCalibrationIntercept"))
        self.gridLayout.addWidget(self.doubleSpinBoxCalibrationIntercept, 9, 7, 1, 1)
        self.labelTestType = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTestType.sizePolicy().hasHeightForWidth())
        self.labelTestType.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTestType.setFont(font)
        self.labelTestType.setObjectName(_fromUtf8("labelTestType"))
        self.gridLayout.addWidget(self.labelTestType, 0, 5, 1, 3)
        self.labelFiles = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFiles.sizePolicy().hasHeightForWidth())
        self.labelFiles.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFiles.setFont(font)
        self.labelFiles.setObjectName(_fromUtf8("labelFiles"))
        self.gridLayout.addWidget(self.labelFiles, 0, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.spinBoxAreaTarget = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBoxAreaTarget.setMaximum(500000)
        self.spinBoxAreaTarget.setObjectName(_fromUtf8("spinBoxAreaTarget"))
        self.gridLayout.addWidget(self.spinBoxAreaTarget, 7, 2, 1, 1)
        self.labelDataDirectory = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDataDirectory.sizePolicy().hasHeightForWidth())
        self.labelDataDirectory.setSizePolicy(sizePolicy)
        self.labelDataDirectory.setObjectName(_fromUtf8("labelDataDirectory"))
        self.gridLayout.addWidget(self.labelDataDirectory, 1, 1, 1, 1)
        self.toolButtonResultsFile = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonResultsFile.setObjectName(_fromUtf8("toolButtonResultsFile"))
        self.gridLayout.addWidget(self.toolButtonResultsFile, 2, 3, 1, 1)
        self.lineEditResultsFile = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditResultsFile.setObjectName(_fromUtf8("lineEditResultsFile"))
        self.gridLayout.addWidget(self.lineEditResultsFile, 2, 2, 1, 1)
        self.radioButtonC10_C40 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButtonC10_C40.setObjectName(_fromUtf8("radioButtonC10_C40"))
        self.gridLayout.addWidget(self.radioButtonC10_C40, 2, 6, 1, 1)
        self.labelAreaTarget = QtGui.QLabel(self.gridLayoutWidget)
        self.labelAreaTarget.setObjectName(_fromUtf8("labelAreaTarget"))
        self.gridLayout.addWidget(self.labelAreaTarget, 7, 1, 1, 1)
        self.doubleSpinBoxDilutionFactor = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxDilutionFactor.setDecimals(3)
        self.doubleSpinBoxDilutionFactor.setMaximum(10.0)
        self.doubleSpinBoxDilutionFactor.setSingleStep(0.001)
        self.doubleSpinBoxDilutionFactor.setObjectName(_fromUtf8("doubleSpinBoxDilutionFactor"))
        self.gridLayout.addWidget(self.doubleSpinBoxDilutionFactor, 5, 7, 1, 1)
        self.lineEditDataDirectory = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditDataDirectory.setObjectName(_fromUtf8("lineEditDataDirectory"))
        self.gridLayout.addWidget(self.lineEditDataDirectory, 1, 2, 1, 1)
        self.doubleSpinBoxRtTarget = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxRtTarget.setDecimals(3)
        self.doubleSpinBoxRtTarget.setMaximum(100.0)
        self.doubleSpinBoxRtTarget.setSingleStep(0.001)
        self.doubleSpinBoxRtTarget.setObjectName(_fromUtf8("doubleSpinBoxRtTarget"))
        self.gridLayout.addWidget(self.doubleSpinBoxRtTarget, 5, 2, 1, 1)
        self.toolButtonDataDirectory = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonDataDirectory.setObjectName(_fromUtf8("toolButtonDataDirectory"))
        self.gridLayout.addWidget(self.toolButtonDataDirectory, 1, 3, 1, 1)
        self.labelAnalysisDetails = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAnalysisDetails.setFont(font)
        self.labelAnalysisDetails.setObjectName(_fromUtf8("labelAnalysisDetails"))
        self.gridLayout.addWidget(self.labelAnalysisDetails, 4, 5, 1, 3)
        self.labelRtTolerance = QtGui.QLabel(self.gridLayoutWidget)
        self.labelRtTolerance.setObjectName(_fromUtf8("labelRtTolerance"))
        self.gridLayout.addWidget(self.labelRtTolerance, 6, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.labelResultsFile = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelResultsFile.sizePolicy().hasHeightForWidth())
        self.labelResultsFile.setSizePolicy(sizePolicy)
        self.labelResultsFile.setObjectName(_fromUtf8("labelResultsFile"))
        self.gridLayout.addWidget(self.labelResultsFile, 2, 1, 1, 1)
        self.labelDilutionFactor = QtGui.QLabel(self.gridLayoutWidget)
        self.labelDilutionFactor.setObjectName(_fromUtf8("labelDilutionFactor"))
        self.gridLayout.addWidget(self.labelDilutionFactor, 5, 6, 1, 1)
        self.doubleSpinBoxRtTolerance = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxRtTolerance.setDecimals(3)
        self.doubleSpinBoxRtTolerance.setMaximum(10.0)
        self.doubleSpinBoxRtTolerance.setSingleStep(0.001)
        self.doubleSpinBoxRtTolerance.setObjectName(_fromUtf8("doubleSpinBoxRtTolerance"))
        self.gridLayout.addWidget(self.doubleSpinBoxRtTolerance, 6, 2, 1, 1)
        self.labelConcentration = QtGui.QLabel(self.gridLayoutWidget)
        self.labelConcentration.setObjectName(_fromUtf8("labelConcentration"))
        self.gridLayout.addWidget(self.labelConcentration, 9, 1, 1, 1)
        self.labelRtTarget = QtGui.QLabel(self.gridLayoutWidget)
        self.labelRtTarget.setObjectName(_fromUtf8("labelRtTarget"))
        self.gridLayout.addWidget(self.labelRtTarget, 5, 1, 1, 1)
        self.doubleSpinBoxConcentration = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBoxConcentration.setMaximum(500.0)
        self.doubleSpinBoxConcentration.setSingleStep(0.01)
        self.doubleSpinBoxConcentration.setObjectName(_fromUtf8("doubleSpinBoxConcentration"))
        self.gridLayout.addWidget(self.doubleSpinBoxConcentration, 9, 2, 1, 1)
        self.labelAreaTolerance = QtGui.QLabel(self.gridLayoutWidget)
        self.labelAreaTolerance.setObjectName(_fromUtf8("labelAreaTolerance"))
        self.gridLayout.addWidget(self.labelAreaTolerance, 8, 1, 1, 1)
        self.radioButtonC6_C10 = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButtonC6_C10.setObjectName(_fromUtf8("radioButtonC6_C10"))
        self.gridLayout.addWidget(self.radioButtonC6_C10, 1, 6, 1, 1)
        self.spinBoxAreaTolerance = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBoxAreaTolerance.setMaximum(500000)
        self.spinBoxAreaTolerance.setObjectName(_fromUtf8("spinBoxAreaTolerance"))
        self.gridLayout.addWidget(self.spinBoxAreaTolerance, 8, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 7, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 5, 1, 1)
        self.labelCalibrationSlope = QtGui.QLabel(self.gridLayoutWidget)
        self.labelCalibrationSlope.setObjectName(_fromUtf8("labelCalibrationSlope"))
        self.gridLayout.addWidget(self.labelCalibrationSlope, 8, 6, 1, 1)
        self.labelCalibrationIntercept = QtGui.QLabel(self.gridLayoutWidget)
        self.labelCalibrationIntercept.setObjectName(_fromUtf8("labelCalibrationIntercept"))
        self.gridLayout.addWidget(self.labelCalibrationIntercept, 9, 6, 1, 1)
        self.line_3 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 6, 5, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 5, 1, 3)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 4)
        self.labelCalibration = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCalibration.sizePolicy().hasHeightForWidth())
        self.labelCalibration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCalibration.setFont(font)
        self.labelCalibration.setObjectName(_fromUtf8("labelCalibration"))
        self.gridLayout.addWidget(self.labelCalibration, 7, 5, 1, 3)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 50, 651, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.pushButtonStart = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(280, 390, 135, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStart.sizePolicy().hasHeightForWidth())
        self.pushButtonStart.setSizePolicy(sizePolicy)
        self.pushButtonStart.setFlat(False)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 370, 651, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Org-Process v1.0", None))
        self.labelIstd.setText(_translate("MainWindow", "ISTD Details", None))
        self.labelTestType.setText(_translate("MainWindow", "Test Type", None))
        self.labelFiles.setText(_translate("MainWindow", "Files", None))
        self.labelDataDirectory.setText(_translate("MainWindow", "Data Directory", None))
        self.toolButtonResultsFile.setText(_translate("MainWindow", "...", None))
        self.radioButtonC10_C40.setText(_translate("MainWindow", "TRH >C10-C40", None))
        self.labelAreaTarget.setText(_translate("MainWindow", "Area Target", None))
        self.toolButtonDataDirectory.setText(_translate("MainWindow", "...", None))
        self.labelAnalysisDetails.setText(_translate("MainWindow", "Analysis Details", None))
        self.labelRtTolerance.setText(_translate("MainWindow", "Retention Time Tolerance", None))
        self.labelResultsFile.setText(_translate("MainWindow", "Results File", None))
        self.labelDilutionFactor.setText(_translate("MainWindow", "Dilution Factor", None))
        self.labelConcentration.setText(_translate("MainWindow", "Concentration (ug/L)", None))
        self.labelRtTarget.setText(_translate("MainWindow", "Retention Time Target", None))
        self.labelAreaTolerance.setText(_translate("MainWindow", "Area Tolerance", None))
        self.radioButtonC6_C10.setText(_translate("MainWindow", "TRH C6-C10", None))
        self.labelCalibrationSlope.setText(_translate("MainWindow", "Calibration Slope (m)", None))
        self.labelCalibrationIntercept.setText(_translate("MainWindow", "Calibration Intercept (c)", None))
        self.labelCalibration.setText(_translate("MainWindow", "Calibration Details", None))
        self.label_6.setText(_translate("MainWindow", "Org-Process v1.0", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start Calculation", None))

