# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'org-process-ui_v02.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(11, 20, 771, 531))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBoxFiles = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxFiles.setFlat(False)
        self.groupBoxFiles.setObjectName(_fromUtf8("groupBoxFiles"))
        self.gridLayoutWidget = QtGui.QWidget(self.groupBoxFiles)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 341, 231))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutFiles = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutFiles.setObjectName(_fromUtf8("gridLayoutFiles"))
        self.labelResultsLocation = QtGui.QLabel(self.gridLayoutWidget)
        self.labelResultsLocation.setObjectName(_fromUtf8("labelResultsLocation"))
        self.gridLayoutFiles.addWidget(self.labelResultsLocation, 1, 1, 1, 1)
        self.toolButtonDataDirectory = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonDataDirectory.setObjectName(_fromUtf8("toolButtonDataDirectory"))
        self.gridLayoutFiles.addWidget(self.toolButtonDataDirectory, 0, 4, 1, 1)
        self.lineEditDataDirectory = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditDataDirectory.setObjectName(_fromUtf8("lineEditDataDirectory"))
        self.gridLayoutFiles.addWidget(self.lineEditDataDirectory, 0, 3, 1, 1)
        self.labelDataDirectory = QtGui.QLabel(self.gridLayoutWidget)
        self.labelDataDirectory.setObjectName(_fromUtf8("labelDataDirectory"))
        self.gridLayoutFiles.addWidget(self.labelDataDirectory, 0, 1, 1, 1)
        self.lineEditResultsLocation = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEditResultsLocation.setObjectName(_fromUtf8("lineEditResultsLocation"))
        self.gridLayoutFiles.addWidget(self.lineEditResultsLocation, 1, 3, 1, 1)
        self.toolButtonResultsLocation = QtGui.QToolButton(self.gridLayoutWidget)
        self.toolButtonResultsLocation.setObjectName(_fromUtf8("toolButtonResultsLocation"))
        self.gridLayoutFiles.addWidget(self.toolButtonResultsLocation, 1, 4, 1, 1)
        self.gridLayoutWidget.raise_()
        self.verticalLayout.addWidget(self.groupBoxFiles)
        self.groupBoxIstd = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxIstd.setObjectName(_fromUtf8("groupBoxIstd"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBoxIstd)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(19, 19, 341, 221))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayoutIstd = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayoutIstd.setObjectName(_fromUtf8("gridLayoutIstd"))
        self.labelRtTarget = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelRtTarget.setObjectName(_fromUtf8("labelRtTarget"))
        self.gridLayoutIstd.addWidget(self.labelRtTarget, 0, 0, 1, 1)
        self.doubleSpinBoxRtTarget = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBoxRtTarget.setObjectName(_fromUtf8("doubleSpinBoxRtTarget"))
        self.gridLayoutIstd.addWidget(self.doubleSpinBoxRtTarget, 0, 1, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayoutIstd.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.spinBoxAreaTarget = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.spinBoxAreaTarget.setObjectName(_fromUtf8("spinBoxAreaTarget"))
        self.gridLayoutIstd.addWidget(self.spinBoxAreaTarget, 2, 1, 1, 1)
        self.doubleSpinBoxConcentration = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBoxConcentration.setObjectName(_fromUtf8("doubleSpinBoxConcentration"))
        self.gridLayoutIstd.addWidget(self.doubleSpinBoxConcentration, 4, 1, 1, 1)
        self.labelAreaTarget = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelAreaTarget.setObjectName(_fromUtf8("labelAreaTarget"))
        self.gridLayoutIstd.addWidget(self.labelAreaTarget, 2, 0, 1, 1)
        self.labelRtTolerance = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelRtTolerance.setObjectName(_fromUtf8("labelRtTolerance"))
        self.gridLayoutIstd.addWidget(self.labelRtTolerance, 1, 0, 1, 1)
        self.labelConcentration = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelConcentration.setObjectName(_fromUtf8("labelConcentration"))
        self.gridLayoutIstd.addWidget(self.labelConcentration, 4, 0, 1, 1)
        self.spinBoxAreaTolerance = QtGui.QSpinBox(self.gridLayoutWidget_3)
        self.spinBoxAreaTolerance.setObjectName(_fromUtf8("spinBoxAreaTolerance"))
        self.gridLayoutIstd.addWidget(self.spinBoxAreaTolerance, 3, 1, 1, 1)
        self.labelAreaTolerance = QtGui.QLabel(self.gridLayoutWidget_3)
        self.labelAreaTolerance.setObjectName(_fromUtf8("labelAreaTolerance"))
        self.gridLayoutIstd.addWidget(self.labelAreaTolerance, 3, 0, 1, 1)
        self.horizontalSliderRtTarget = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSliderRtTarget.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRtTarget.setObjectName(_fromUtf8("horizontalSliderRtTarget"))
        self.gridLayoutIstd.addWidget(self.horizontalSliderRtTarget, 0, 2, 1, 1)
        self.horizontalSlider_2 = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.gridLayoutIstd.addWidget(self.horizontalSlider_2, 1, 2, 1, 1)
        self.horizontalSliderAreaTarget = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSliderAreaTarget.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAreaTarget.setObjectName(_fromUtf8("horizontalSliderAreaTarget"))
        self.gridLayoutIstd.addWidget(self.horizontalSliderAreaTarget, 2, 2, 1, 1)
        self.horizontalSlideAreaTolerance = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSlideAreaTolerance.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlideAreaTolerance.setObjectName(_fromUtf8("horizontalSlideAreaTolerance"))
        self.gridLayoutIstd.addWidget(self.horizontalSlideAreaTolerance, 3, 2, 1, 1)
        self.horizontalSliderConcentration = QtGui.QSlider(self.gridLayoutWidget_3)
        self.horizontalSliderConcentration.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderConcentration.setObjectName(_fromUtf8("horizontalSliderConcentration"))
        self.gridLayoutIstd.addWidget(self.horizontalSliderConcentration, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxIstd)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBoxTestType = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxTestType.setObjectName(_fromUtf8("groupBoxTestType"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBoxTestType)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(19, 29, 341, 81))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayoutTestType = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayoutTestType.setObjectName(_fromUtf8("verticalLayoutTestType"))
        self.radioButtonC6_C10 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButtonC6_C10.setObjectName(_fromUtf8("radioButtonC6_C10"))
        self.verticalLayoutTestType.addWidget(self.radioButtonC6_C10)
        self.radioButtonC10_C40 = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButtonC10_C40.setObjectName(_fromUtf8("radioButtonC10_C40"))
        self.verticalLayoutTestType.addWidget(self.radioButtonC10_C40)
        self.verticalLayout_2.addWidget(self.groupBoxTestType)
        self.groupBoxAnalysis = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxAnalysis.setObjectName(_fromUtf8("groupBoxAnalysis"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBoxAnalysis)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 29, 341, 81))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelDilutionFactor = QtGui.QLabel(self.formLayoutWidget)
        self.labelDilutionFactor.setObjectName(_fromUtf8("labelDilutionFactor"))
        self.gridLayout.addWidget(self.labelDilutionFactor, 0, 0, 1, 1)
        self.doubleSpinBoxDilutionFactor = QtGui.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBoxDilutionFactor.setObjectName(_fromUtf8("doubleSpinBoxDilutionFactor"))
        self.gridLayout.addWidget(self.doubleSpinBoxDilutionFactor, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxAnalysis)
        self.groupBoxCalibration = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBoxCalibration.setObjectName(_fromUtf8("groupBoxCalibration"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBoxCalibration)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(19, 19, 341, 91))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayoutCalibration = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutCalibration.setObjectName(_fromUtf8("gridLayoutCalibration"))
        self.labelCalibrationSlope = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelCalibrationSlope.setObjectName(_fromUtf8("labelCalibrationSlope"))
        self.gridLayoutCalibration.addWidget(self.labelCalibrationSlope, 0, 0, 1, 1)
        self.labelCalibrationIntercept = QtGui.QLabel(self.gridLayoutWidget_2)
        self.labelCalibrationIntercept.setObjectName(_fromUtf8("labelCalibrationIntercept"))
        self.gridLayoutCalibration.addWidget(self.labelCalibrationIntercept, 1, 0, 1, 1)
        self.doubleSpinBoxCalibrationSlope = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBoxCalibrationSlope.setObjectName(_fromUtf8("doubleSpinBoxCalibrationSlope"))
        self.gridLayoutCalibration.addWidget(self.doubleSpinBoxCalibrationSlope, 0, 1, 1, 1)
        self.doubleSpinBoxCalibrationIntercept = QtGui.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBoxCalibrationIntercept.setObjectName(_fromUtf8("doubleSpinBoxCalibrationIntercept"))
        self.gridLayoutCalibration.addWidget(self.doubleSpinBoxCalibrationIntercept, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBoxCalibration)
        self.horizontalLayoutStart = QtGui.QHBoxLayout()
        self.horizontalLayoutStart.setObjectName(_fromUtf8("horizontalLayoutStart"))
        self.pushButtonStart = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStart.sizePolicy().hasHeightForWidth())
        self.pushButtonStart.setSizePolicy(sizePolicy)
        self.pushButtonStart.setFlat(False)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.horizontalLayoutStart.addWidget(self.pushButtonStart)
        self.verticalLayout_2.addLayout(self.horizontalLayoutStart)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Org-Process v1.0", None))
        self.groupBoxFiles.setTitle(_translate("MainWindow", "Files", None))
        self.labelResultsLocation.setText(_translate("MainWindow", "Results Location", None))
        self.toolButtonDataDirectory.setText(_translate("MainWindow", "...", None))
        self.labelDataDirectory.setText(_translate("MainWindow", "Data Directory", None))
        self.toolButtonResultsLocation.setText(_translate("MainWindow", "...", None))
        self.groupBoxIstd.setTitle(_translate("MainWindow", "ISTD Details", None))
        self.labelRtTarget.setText(_translate("MainWindow", "Retention Time Target", None))
        self.labelAreaTarget.setText(_translate("MainWindow", "Area Target", None))
        self.labelRtTolerance.setText(_translate("MainWindow", "Retention Time Tolerance", None))
        self.labelConcentration.setText(_translate("MainWindow", "Concentration (ug/L)", None))
        self.labelAreaTolerance.setText(_translate("MainWindow", "Area Tolerance", None))
        self.groupBoxTestType.setTitle(_translate("MainWindow", "Test Type", None))
        self.radioButtonC6_C10.setText(_translate("MainWindow", "TRH C6-C10", None))
        self.radioButtonC10_C40.setText(_translate("MainWindow", "TRH >C10-C40", None))
        self.groupBoxAnalysis.setTitle(_translate("MainWindow", "Analysis Details", None))
        self.labelDilutionFactor.setText(_translate("MainWindow", "Dilution Factor", None))
        self.groupBoxCalibration.setTitle(_translate("MainWindow", "Calibration Details", None))
        self.labelCalibrationSlope.setText(_translate("MainWindow", "Calibration Slope (m)", None))
        self.labelCalibrationIntercept.setText(_translate("MainWindow", "Calibration Intercept (c)", None))
        self.pushButtonStart.setText(_translate("MainWindow", "Start Calculation", None))

